### ISSUE TITLE
1247-jndi启动报错

### ISSUE THREAD

**Issue by kmustriver** [lemono0/FastJsonParty#4]
[root@VM-0-9-opencloudos 1247-jndi]# docker compose up
[+] Running 1/0
 ✔ Container 1247-jndi-web-1  Created                                                                                                         0.0s
Attaching to 1247-jndi-web-1
1247-jndi-web-1  |
1247-jndi-web-1  |   .   ____          _            __ _ _
1247-jndi-web-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
1247-jndi-web-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
1247-jndi-web-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
1247-jndi-web-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
1247-jndi-web-1  |  =========|_|==============|___/=/_/_/_/
1247-jndi-web-1  |  :: Spring Boot ::        (v2.2.7.RELEASE)
1247-jndi-web-1  |
1247-jndi-web-1  |
1247-jndi-web-1  | 2024-07-10 10:03:25.030  INFO 1 --- [           main] com.lemono.FastjsonPartyDemoApplication  : Starting FastjsonPartyDemoApplication v0.0.1-SNAPSHOT on ca09c60de0f9 with PID 1 (/var/app/1247-jndi.jar started by ctf in /var/app)
1247-jndi-web-1  | 2024-07-10 10:03:25.034  INFO 1 --- [           main] com.lemono.FastjsonPartyDemoApplication  : No active profile set, falling back to default profiles: default
1247-jndi-web-1  | 2024-07-10 10:03:26.398  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 80 (http)
1247-jndi-web-1  | 2024-07-10 10:03:26.413  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
1247-jndi-web-1  | 2024-07-10 10:03:26.413  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.34]
1247-jndi-web-1  | 2024-07-10 10:03:26.490  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
1247-jndi-web-1  | 2024-07-10 10:03:26.490  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1382 ms
1247-jndi-web-1  | 2024-07-10 10:03:26.686  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
1247-jndi-web-1  | 2024-07-10 10:03:26.764  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
1247-jndi-web-1  | 2024-07-10 10:03:26.878  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
1247-jndi-web-1  | 2024-07-10 10:03:26.885  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :
1247-jndi-web-1  |
1247-jndi-web-1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
1247-jndi-web-1  |
1247-jndi-web-1  | 2024-07-10 10:03:26.890 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
1247-jndi-web-1  |
1247-jndi-web-1  | org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
1247-jndi-web-1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:212) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:297) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at com.lemono.FastjsonPartyDemoApplication.main(FastjsonPartyDemoApplication.java:12) [classes!/:0.0.1-SNAPSHOT]
1247-jndi-web-1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [1247-jndi.jar:0.0.1-SNAPSHOT]
1247-jndi-web-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [1247-jndi.jar:0.0.1-SNAPSHOT]
1247-jndi-web-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [1247-jndi.jar:0.0.1-SNAPSHOT]
1247-jndi-web-1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [1247-jndi.jar:0.0.1-SNAPSHOT]
1247-jndi-web-1  | Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
1247-jndi-web-1  | 	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:231) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:265) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:196) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
1247-jndi-web-1  | 	... 18 common frames omitted
1247-jndi-web-1  | Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
1247-jndi-web-1  | 	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1066) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:227) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	... 20 common frames omitted
1247-jndi-web-1  | Caused by: java.net.SocketException: Permission denied
1247-jndi-web-1  | 	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[na:1.8.0_121]
1247-jndi-web-1  | 	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:228) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:211) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1141) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1227) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:592) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1063) ~[tomcat-embed-core-9.0.34.jar!/:9.0.34]
1247-jndi-web-1  | 	... 22 common frames omitted
1247-jndi-web-1  |
1247-jndi-web-1  |
1247-jndi-web-1  | 2024-07-10 10:03:26.893  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
1247-jndi-web-1 exited with code 1

**Comment by eonun** [comment]
修改一下 `docker-compose.yml`，使用root用户来执行
```yml
version: '2'
services:
  web:
    image: lemono0/fastjsonparty:1247-jndi
    ports:
      - "8080:80"
    user: root
```

不知道为什么作者将 `fastjsonparty:1247-jndi` 这个镜像制作成使用普通权限来执行，是漏洞需要吗
